"""API pubblica di contracts."""

from .core import (
    STATE_FEATURES_PER_OBJECT,
    ObjectObservation,
    Observation,
    PrivilegedState,
    ObjectDecision,
    ExecutionOutcome,
    TaskOutcome,
)
from .observation import (
    PerceptualObject,
    PerceptualState,
    SensorEvidence,
    SensorBundle,
    TaskContext,
    SceneObject,
    SceneState,
    PhysicalRelation,
    PhysicalRelationState,
    ObjectUncertainty,
    UncertaintyState,
    ObservationInvariantError,
    validate_observation,
)
from .sensing import (
    Detection,
    LidarFrame,
    SensorCalibration,
    StereoFrame,
    SynchronizedSensorPacket,
)

__all__ = [
    "STATE_FEATURES_PER_OBJECT",
    "ObjectObservation",
    "Observation",
    "PrivilegedState",
    "ObjectDecision",
    "ExecutionOutcome",
    "TaskOutcome",
    "PerceptualObject",
    "PerceptualState",
    "SensorEvidence",
    "SensorBundle",
    "TaskContext",
    "SceneObject",
    "SceneState",
    "PhysicalRelation",
    "PhysicalRelationState",
    "ObjectUncertainty",
    "UncertaintyState",
    "ObservationInvariantError",
    "validate_observation",
    "Detection",
    "LidarFrame",
    "SensorCalibration",
    "StereoFrame",
    "SynchronizedSensorPacket",
]
